### PR TITLE
Added terminator to gracefully exit optimisation.

### PR DESCRIPTION
**Pull request by AurelienJaquier**

### CODE REVIEW

**Comment by wvangeit** [comment]
You think a test could be added for this?

**Comment by AurelienJaquier** [comment]
If we can play with multiprocessing with Jenkins, I could write a small test to see if the new run_next_gen function gets triggered when terminator is set in another process. I'll have a look into it.

**Comment by wvangeit** [comment]
We don't need this in master?

**Comment by DrTaDa** [comment]
@AurelienJaquier chose this branch because it's the one used in BluePyEModel but it's true that it could be better if we had that into master.

**Pull request merged**
