### PR TITLE
Update l5pc example benchmark for numpy.float deprecation

### PR DESCRIPTION
**Pull request by musicinmybrain**

### CODE REVIEW

**Review by anilbey — APPROVED** [review]

**Review by AurelienJaquier — APPROVED** [review]

**Comment by anilbey** [comment]
The CI failure is not related to this PR, it's because of the following release of NEURON-nightly: `NEURON-nightly 9.0.dev1289 `.

**Comment by wvangeit** [comment]
So they basically dropped Py 3.7 support I guess?

**Comment by anilbey** [comment]
Ah yes 3.8 works, shall we drop 3.7 as well?

**Comment by wvangeit** [comment]
It depends a bit on how common py 3.7 is still used at the moment. Do you know what the default python in ubuntu LTS at the moment?

**Comment by anilbey** [comment]
Python3.7 ends in 4 months.
https://endoflife.date/python

Ubuntu LTS (22.04) comes with python3.10.4.
https://utcc.utoronto.ca/~cks/space/blog/python/Ubuntu2204PythonState

**Comment by wvangeit** [comment]
Ok, if it ends in 4 months it's ok, we can already drop the support.

**Comment by anilbey** [comment]
https://github.com/BlueBrain/BluePyOpt/pull/446 is created to drop py3.7 support.

**Comment by wvangeit** [comment]
Thank you @musicinmybrain for your contribution!

**Pull request merged**
