### PR TITLE
remove __future__ imports

### PR DESCRIPTION
**Pull request by AurelienJaquier**
I only removed one line in each jupyter notebook, and it does not look like anything else has changed, when checking visually. @anilbey do you know why other lines have been unilateraly changed here?

### CODE REVIEW

**Comment by anilbey** [comment]
Nice change.

Yeah jupyter and git do these. Those differences must be created after you execute the cells.

**Comment by anilbey** [comment]
So I think if you git reset and then remove the lines and not execute the notebook cells then it should not add those.

**Comment by AurelienJaquier** [comment]
I actually did not execute the cells. I just removed the line, and saved in VScode.

**Comment by anilbey** [comment]
Oh, I see. Hmm if vscode did something and not displayed it, then the javascript lines can still be selected via `git add -p PATH_TO_NOTEBOOK` if you want to remove them.

**Pull request merged**
