### PR TITLE
remove ineffective checks against python2

### PR DESCRIPTION
**Pull request by anilbey**

### CODE REVIEW

**Comment by anilbey** [comment]
@wvangeit I think only you have the authority to merge

**Comment by wvangeit** [comment]
Is there any specific reason to remove these lines, apart from readability?
I don't really feel like breaking compatibility just for the sake of breaking compatibility. I'm just worried there might be some users using notebooks on old systems etc.

**Comment by anilbey** [comment]
No, only readability and a bit of confusion :)
E.g. `from __future__` is not the future but the past now

**Comment by wvangeit** [comment]
Ok, but I don't consider that enough arguments to possibly break external user's scripts.

**Comment by anilbey** [comment]
Ok, sure. I'm closing.

**Pull request closed without merging**
