### PR TITLE
restart optimization with modified fitness - resolves #252

### LINKED ISSUE #252: Start/Restart an optimization with a deap population
Hi,
I would like to start/restart optimization with a population rather than just specifying a random seed. This would really help if after **_n_** generations I want to change the fitness function and reinitialize the optimization with the population at the **_n_**_th generation.

Thanks

### PR DESCRIPTION
**Pull request by anirban6908**
Hi @wvangeit ,
Sorry for the delayed PR. Hope this helps.
Thanks

### CODE REVIEW

**Comment by wvangeit** [comment]
Sorry, I'm not completely sure I understand your point.
Do you mean that you want to combine the checkpoints with the 'pop' argument ?

**Comment by anirban6908** [comment]
No, my priority was to have one checkpoint if it's a continuation of an optimization. Ideally pop and continue_cp will not be passed together. 
1. With just pop the optimization will treat this as new run with the list,
2. with continue_cp and reboot_fitness the optimization will change the fitness,select new parents but keep accumulating to the same checkpoint file. 
3. With just continue_cp it will keep the previous behavior (i.e. throwing an error if fitness is modified).
4. When all 3 are passed together the list provided in pop takes priority and accumulates history in the checkpoint file provided.
5. When pop and continue_cp (without reboot_fitness) is passed together (probably by mistake since it probably means you wanted to change fitness) it will take the population from checkpoint and throw error if fitness is modified same as in 3.

**Comment by wvangeit** [comment]
Hi @anirban6908 
Just FYI, I don't mind we still incorporate this. I was just a bit busy the last couple of weeks, so didn't have time to work on this.

**Comment by anirban6908** [comment]
Cool. Let me know if you want me to make any edits.
Thanks

**Pull request closed without merging**
