### PR TITLE
Implement LFPy backend and extracellular features

### PR DESCRIPTION
**Pull request by alejoe91**
- Added LFPy as a backend for simulation
     - [LFPyCellModel](https://github.com/alejoe91/BluePyOpt/blob/merging/bluepyopt/ephys/models.py#L484)
     - [LFPySimulator](https://github.com/alejoe91/BluePyOpt/blob/merging/bluepyopt/ephys/simulators.py#L178)
     - [LFPySquarePulse](https://github.com/alejoe91/BluePyOpt/blob/merging/bluepyopt/ephys/stimuli.py#L341)
     - [TimeLFPResponse](https://github.com/alejoe91/BluePyOpt/blob/merging/bluepyopt/ephys/responses.py#L89)
- Added extracellular efeatures class [extraFELFeature](https://github.com/alejoe91/BluePyOpt/blob/merging/bluepyopt/ephys/efeatures.py#L248) that supports computing features from extracellular "template" (avg action potential). Features include:
    - "peak_to_valley": duration between negative and positive peak
    - "halfwidth": full width alf maximum of negative peak
    - "peak_trough_ratio": ratio between peak and trough
    - "repolarization_slope": slope from the first peak to baseline 
    - "recovery_slope": slop from second peak to baseline
    - "neg_peak_relative": relative amplitude of negative peaks with respect to max channel
    - "pos_peak_relative": relative amplitude of positive peaks with respect to max channel
    - "neg_peak_diff": relative timing of negative peaks with respect to max channel
    - "pos_peak_diff": relative timing of positive peaks with respect to max channel
    - "neg_image": normalized potential at time of negative peak 
    - "pos_image": normalized potential at time of positive peak 

Need to rebase to master once https://github.com/BlueBrain/BluePyOpt/pull/383 is merged.

### CODE REVIEW

**Comment by alejoe91** [comment]
@DrTaDa @AurelienJaquier can you add some small tests for the LFPy classes? To set an `electrode` for the `LFPySimulator`, you can simply do:
```
import MEAutility as mu

mea_info = {
    'dim': mea_dim,
    'electrode_name': 'hd-mea',
    'pitch': mea_pitch,
    'shape': 'square',
    'size': 5,
    'type': 'mea',
    'plane': 'xy'
}
probe = mu.return_mea(info=mea_info)

# Move the MEA out of the neuron plane (yz)
probe.move([0, 0, -20])
```

Let me know if you need any help!

**Comment by DrTaDa** [comment]
@alejoe91 you applied  some automatic reformatting of the code. It would be best if that was rolled back to keep the original BluePyOpt formatting.

**Comment by DrTaDa** [comment]
I will have a look at the tests.

**Comment by alejoe91** [comment]
> @alejoe91 you applied some automatic reformatting of the code. It would be best if that was rolled back to keep the original BluePyOpt formatting.

Oups! Probably easier for me to make a new PR then...

**Comment by alejoe91** [comment]
Closing for a cleaner one

**Pull request closed without merging**
